// --- set error const
const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    TEST_INPUT_INVALID: 460,
    TEST_CONFIGURATION_ERROR: 461,
    INTERNAL_SERVER_ERROR: 500,
    TEST_TIMEOUT: 562,
    TEST_SETUP_FAILED: 563,
};

module.exports = { HTTP_STATUS };